services:
  - type: web
    name: tradebot-flask
    env: python 3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker app:app
    envVars:
      - key: SESSION_SECRET
        value: your-session-secret
      - key: DATABASE_URL
        value: your-database-url
      - key: TELEGRAM_TOKEN
        value: your-telegram-token
      - key: TELEGRAM_CHAT_ID
        value: your-telegram-chat-id
      - key: APP_PACKAGE
        value: com.metaquotes.metatrader5
      - key: APP_ACTIVITY
        value: .MainActivity
    pythonVersion: 3.10.4  # Specify the compatible Python version

  - type: web
    name: appium-server
    env: docker
    dockerfilePath: ./Dockerfile
    port: 4723
